// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package networkacl

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadNetworkacl returns the embedded CollectionSpec for networkacl.
func loadNetworkacl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkaclBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load networkacl: %w", err)
	}

	return spec, err
}

// loadNetworkaclObjects loads networkacl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*networkaclObjects
//	*networkaclPrograms
//	*networkaclMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetworkaclObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetworkacl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// networkaclSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkaclSpecs struct {
	networkaclProgramSpecs
	networkaclMapSpecs
}

// networkaclSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkaclProgramSpecs struct {
	SandboxdAclEgress  *ebpf.ProgramSpec `ebpf:"sandboxd_acl_egress"`
	SandboxdAclIngress *ebpf.ProgramSpec `ebpf:"sandboxd_acl_ingress"`
}

// networkaclMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkaclMapSpecs struct {
	CONFIG_MAP   *ebpf.MapSpec `ebpf:"CONFIG_MAP"`
	CONN_V2MAP   *ebpf.MapSpec `ebpf:"CONN_V2_MAP"`
	DOMAIN_V2MAP *ebpf.MapSpec `ebpf:"DOMAIN_V2_MAP"`
	FRAGMENT_MAP *ebpf.MapSpec `ebpf:"FRAGMENT_MAP"`
	POLICY_MAP   *ebpf.MapSpec `ebpf:"POLICY_MAP"`
	POLICY_V2MAP *ebpf.MapSpec `ebpf:"POLICY_V2_MAP"`
	RULE_MAP     *ebpf.MapSpec `ebpf:"RULE_MAP"`
}

// networkaclObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetworkaclObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkaclObjects struct {
	networkaclPrograms
	networkaclMaps
}

func (o *networkaclObjects) Close() error {
	return _NetworkaclClose(
		&o.networkaclPrograms,
		&o.networkaclMaps,
	)
}

// networkaclMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetworkaclObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkaclMaps struct {
	CONFIG_MAP   *ebpf.Map `ebpf:"CONFIG_MAP"`
	CONN_V2MAP   *ebpf.Map `ebpf:"CONN_V2_MAP"`
	DOMAIN_V2MAP *ebpf.Map `ebpf:"DOMAIN_V2_MAP"`
	FRAGMENT_MAP *ebpf.Map `ebpf:"FRAGMENT_MAP"`
	POLICY_MAP   *ebpf.Map `ebpf:"POLICY_MAP"`
	POLICY_V2MAP *ebpf.Map `ebpf:"POLICY_V2_MAP"`
	RULE_MAP     *ebpf.Map `ebpf:"RULE_MAP"`
}

func (m *networkaclMaps) Close() error {
	return _NetworkaclClose(
		m.CONFIG_MAP,
		m.CONN_V2MAP,
		m.DOMAIN_V2MAP,
		m.FRAGMENT_MAP,
		m.POLICY_MAP,
		m.POLICY_V2MAP,
		m.RULE_MAP,
	)
}

// networkaclPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetworkaclObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkaclPrograms struct {
	SandboxdAclEgress  *ebpf.Program `ebpf:"sandboxd_acl_egress"`
	SandboxdAclIngress *ebpf.Program `ebpf:"sandboxd_acl_ingress"`
}

func (p *networkaclPrograms) Close() error {
	return _NetworkaclClose(
		p.SandboxdAclEgress,
		p.SandboxdAclIngress,
	)
}

func _NetworkaclClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed networkacl_bpfel.o
var _NetworkaclBytes []byte
